apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  query:
    metricsStorage:
      type: prometheus
      server-url: http://prometheus.prometheus.svc:32222/
    image: jaegertracing/jaeger-query:1.58.0
    serviceType: NodePort
    nodePort: 30158
  ingress:
    enabled: false
  strategy: Production
  collector:
    replicas: 1
    autoscale: false
    maxReplicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      request:
        cpu: 50m
        memory: 100Mi
  storage:
    type: elasticsearch
    dependencies:
      enabled: false
      schedule: "30 3 * * 0"
    options:
      memory:
        max-traces: 1500
      es:
        server-urls: http://elasticsearch.utilities.svc:9200
        index-prefix: jaeger-k8s-prod
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - tcolp219
