apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-pv-storage
  namespace: observability
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Importante para no perder datos
  storageClassName: gp1
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tmp262
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc-storage
  namespace: observability
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
